// cards.js - News Cards Data
const cardsData = [
    // ====== FALSE (Tin giả hoàn toàn) ======
    {
        id: "c001",
        title: "UỐNG NƯỚC CHANH MỖI SÁNG CÓ THỂ 'DIỆT' MỌI LOẠI VIRUS TRONG 24 GIỜ!",
        titleEn: "DRINKING LEMON WATER EVERY MORNING CAN 'KILL' ALL VIRUSES IN 24 HOURS!",
        topic: "sức khỏe",
        topicEn: "health",
        credibility: 12,
        type: "false",
        baseVirality: 3,
        signals: ["ALL CAPS", "biệt dược kỳ diệu", "không nêu nghiên cứu"],
        signalsEn: ["ALL CAPS", "miracle cure", "no research cited"],
        reveal: "Không có bằng chứng lâm sàng nào chứng minh nước chanh có thể diệt virus. WHO và CDC không khuyến nghị phương pháp này.",
        revealEn: "No clinical evidence proves lemon water can kill viruses. WHO and CDC do not recommend this method.",
        actionHint: "Gắn cờ hoặc kiểm chứng ngay.",
        actionHintEn: "Flag or fact-check immediately.",
        sourceHint: "Tìm kiếm: WHO Mythbusters, CDC health tips",
        sourceHintEn: "Search: WHO Mythbusters, CDC health tips"
    },
    {
        id: "c002",
        title: "Ảnh gấu koala trên xa lộ Melbourne sau cháy rừng tuần này",
        titleEn: "Photo of koala on Melbourne highway after this week's bushfire",
        topic: "khí hậu",
        topicEn: "climate",
        credibility: 35,
        type: "misleading",
        baseVirality: 2,
        signals: ["ảnh cũ tái đăng", "không ghi mốc thời gian", "cảm xúc"],
        signalsEn: ["old photo reposted", "no timestamp", "emotional"],
        reveal: "Ảnh thực tế được chụp năm 2020 ở New South Wales, không phải Melbourne. Tái đăng gây hiểu lầm về địa điểm và thời gian.",
        revealEn: "Photo was actually taken in 2020 in New South Wales, not Melbourne. Repost misleads about location and time.",
        actionHint: "Kiểm chứng hình ảnh bằng tìm kiếm đảo ngược.",
        actionHintEn: "Fact-check image with reverse search.",
        sourceHint: "Dùng Google Images hoặc TinEye để tìm kiếm ảnh gốc",
        sourceHintEn: "Use Google Images or TinEye for reverse image search"
    },
    {
        id: "c003",
        title: "Ứng dụng VinaMoney tặng 5 triệu đồng nếu chia sẻ bài viết này cho 10 bạn bè",
        titleEn: "VinaMoney app gives 5 million VND if you share this post with 10 friends",
        topic: "lừa đảo số",
        topicEn: "digital scam",
        credibility: 8,
        type: "false",
        baseVirality: 3,
        signals: ["quá tốt để thật", "yêu cầu chia sẻ", "URL rút gọn"],
        signalsEn: ["too good to be true", "requires sharing", "shortened URL"],
        reveal: "Đây là chiến thuật lừa đảo phổ biến. Không ứng dụng chính thống nào tặng tiền chỉ vì chia sẻ. Mục đích là thu thập dữ liệu cá nhân.",
        revealEn: "This is a common scam tactic. No legitimate app gives money just for sharing. Purpose is to collect personal data.",
        actionHint: "Báo cáo ngay lập tức.",
        actionHintEn: "Report immediately.",
        sourceHint: "Kiểm tra website chính thức của ngân hàng/ứng dụng",
        sourceHintEn: "Check official bank/app website"
    },
    {
        id: "c004",
        title: "Bão cát kinh hoàng ở TP.HCM tối qua - Video từ người dân ghi lại",
        titleEn: "Terrifying sandstorm in Ho Chi Minh City last night - Video from locals",
        topic: "thời tiết",
        topicEn: "weather",
        credibility: 20,
        type: "false",
        baseVirality: 3,
        signals: ["video nước ngoài", "không có nguồn chính thức", "cảm xúc"],
        signalsEn: ["foreign video", "no official source", "emotional"],
        reveal: "Video thực ra là cảnh bão cát ở Dubai năm 2022. TP.HCM không có hiện tượng bão cát do điều kiện địa lý.",
        revealEn: "Video is actually a sandstorm in Dubai from 2022. HCMC doesn't have sandstorms due to geographical conditions.",
        actionHint: "Kiểm tra với Đài Khí tượng Thủy văn.",
        actionHintEn: "Check with Meteorological Agency.",
        sourceHint: "Xem thông tin từ nchmf.gov.vn",
        sourceHintEn: "Check information from nchmf.gov.vn"
    },
    {
        id: "c005",
        title: "ĂN THỊT BÒ GÂY UNG THƯ 100%! Các chuyên gia ở Úc cảnh báo",
        titleEn: "EATING BEEF CAUSES CANCER 100%! Experts in Australia warn",
        topic: "sức khỏe",
        topicEn: "health",
        credibility: 15,
        type: "false",
        baseVirality: 3,
        signals: ["ALL CAPS", "phóng đại", "không nêu nghiên cứu cụ thể"],
        signalsEn: ["ALL CAPS", "exaggerated", "no specific research cited"],
        reveal: "Thịt đỏ có thể tăng nguy cơ một số bệnh nếu ăn quá nhiều, nhưng không 'gây ung thư 100%'. Nghiên cứu cho thấy mối liên hệ, không phải nhân quả tuyệt đối.",
        revealEn: "Red meat may increase risk of some diseases if consumed excessively, but doesn't 'cause cancer 100%'. Research shows correlation, not absolute causation.",
        actionHint: "Gắn cờ vì phóng đại và gây hoang mang.",
        actionHintEn: "Flag for exaggeration and causing panic.",
        sourceHint: "Tham khảo WHO IARC classification of meats",
        sourceHintEn: "Refer to WHO IARC classification of meats"
    },
    {
        id: "c006",
        title: "Clip người quen của bạn nhắn tin 'chị ơi cho em mượn 2 triệu gấp' qua Messenger",
        titleEn: "Video of your friend messaging 'sis can I borrow 2 million urgently' via Messenger",
        topic: "lừa đảo số",
        topicEn: "digital scam",
        credibility: 10,
        type: "false",
        baseVirality: 2,
        signals: ["tài khoản bị hack", "yêu cầu tiền", "khẩn cấp"],
        signalsEn: ["hacked account", "money request", "urgent"],
        reveal: "Tài khoản Messenger bị hack. Kẻ lừa đảo giả mạo người quen để xin tiền. Luôn xác minh qua điện thoại hoặc gặp trực tiếp.",
        revealEn: "Messenger account was hacked. Scammers impersonate friends to ask for money. Always verify via phone or in person.",
        actionHint: "Báo cáo và liên hệ người quen qua kênh khác.",
        actionHintEn: "Report and contact friend through another channel.",
        sourceHint: "Cảnh báo từ Cục An toàn thông tin Việt Nam",
        sourceHintEn: "Warning from Vietnam Information Security Department"
    },
    {
        id: "c007",
        title: "Tia 5G làm hỏng cây xanh và gây rụng lá hàng loạt ở Hà Nội",
        titleEn: "5G radiation damages trees and causes mass leaf fall in Hanoi",
        topic: "công nghệ",
        topicEn: "technology",
        credibility: 5,
        type: "false",
        baseVirality: 2,
        signals: ["thuyết âm mưu", "không có nghiên cứu", "phóng đại"],
        signalsEn: ["conspiracy theory", "no research", "exaggerated"],
        reveal: "Không có bằng chứng khoa học nào chứng minh sóng 5G ảnh hưởng đến cây xanh. WHO và các tổ chức y tế xác nhận 5G an toàn trong ngưỡng cho phép.",
        revealEn: "No scientific evidence proves 5G waves affect trees. WHO and health organizations confirm 5G is safe within permitted limits.",
        actionHint: "Kiểm chứng với nguồn khoa học uy tín.",
        actionHintEn: "Fact-check with credible scientific sources.",
        sourceHint: "WHO EMF Project, IEEE Standards",
        sourceHintEn: "WHO EMF Project, IEEE Standards"
    },
    {
        id: "c008",
        title: "Máy lọc không khí bỏ túi giá 199k bảo vệ phổi khỏi khói bụi 100%",
        titleEn: "Pocket air purifier for 199k protects lungs from smoke and dust 100%",
        topic: "tiêu dùng",
        topicEn: "consumer",
        credibility: 25,
        type: "misleading",
        baseVirality: 2,
        signals: ["quá rẻ", "khẳng định 100%", "quảng cáo ẩn"],
        signalsEn: ["too cheap", "100% claim", "hidden ad"],
        reveal: "Máy lọc không khí cần có công suất đủ lớn và filter chuẩn để hiệu quả. Sản phẩm giá rẻ thường không đạt chuẩn, chỉ là quạt mini.",
        revealEn: "Air purifiers need sufficient power and standard filters to be effective. Cheap products usually don't meet standards, they're just mini fans.",
        actionHint: "Gắn cờ vì quảng cáo gian lận.",
        actionHintEn: "Flag for fraudulent advertising.",
        sourceHint: "Kiểm tra đánh giá từ các tổ chức độc lập",
        sourceHintEn: "Check reviews from independent organizations"
    },
    {
        id: "c009",
        title: "Ảnh cực quang xuất hiện ở bầu trời Sydney đêm qua - Hiếm gặp",
        titleEn: "Aurora appears in Sydney sky last night - Rare occurrence",
        topic: "thiên văn",
        topicEn: "astronomy",
        credibility: 18,
        type: "false",
        baseVirality: 3,
        signals: ["ảnh AI/fake", "vị trí địa lý sai", "cảm xúc"],
        signalsEn: ["AI/fake image", "wrong location", "emotional"],
        reveal: "Cực quang rất hiếm xuất hiện ở Sydney (vĩ độ thấp). Ảnh có khả năng tạo bằng AI hoặc từ địa điểm khác như Tasmania, New Zealand.",
        revealEn: "Aurora is very rare in Sydney (low latitude). Image likely AI-generated or from another location like Tasmania, New Zealand.",
        actionHint: "Kiểm chứng với Đài thiên văn hoặc chuyên gia.",
        actionHintEn: "Fact-check with Observatory or experts.",
        sourceHint: "Space Weather Prediction Center, Australian Space Academy",
        sourceHintEn: "Space Weather Prediction Center, Australian Space Academy"
    },
    {
        id: "c010",
        title: "BỘ CÔNG AN CẢNH BÁO: Chip trong CCCD gắn chíp có thể bị hack từ xa, rút tiền từ tài khoản",
        titleEn: "MINISTRY OF PUBLIC SECURITY WARNS: Chip in citizen ID can be hacked remotely, money withdrawn from accounts",
        topic: "an ninh",
        topicEn: "security",
        credibility: 10,
        type: "false",
        baseVirality: 3,
        signals: ["ALL CAPS", "gây hoang mang", "thông tin sai"],
        signalsEn: ["ALL CAPS", "fear-mongering", "false information"],
        reveal: "Chip trong CCCD chỉ lưu thông tin cơ bản (ảnh, họ tên, ngày sinh), KHÔNG liên kết trực tiếp với tài khoản ngân hàng. Bộ Công an chưa từng cảnh báo điều này.",
        revealEn: "Chip in citizen ID only stores basic info (photo, name, DOB), NOT directly linked to bank accounts. Ministry has never issued this warning.",
        actionHint: "Báo cáo ngay vì tin giả nghiêm trọng.",
        actionHintEn: "Report immediately for serious misinformation.",
        sourceHint: "Thông tin chính thức từ bocongan.gov.vn",
        sourceHintEn: "Official information from bocongan.gov.vn"
    },

    // ====== MISLEADING (Gây hiểu lầm, thiếu ngữ cảnh) ======
    {
        id: "c011",
        title: "Nghiên cứu: Sét đánh gây cháy rừng nhiều hơn con người",
        titleEn: "Research: Lightning causes more forest fires than humans",
        topic: "khí hậu",
        topicEn: "climate",
        credibility: 55,
        type: "misleading",
        baseVirality: 2,
        signals: ["thiếu ngữ cảnh", "khái quát hóa"],
        signalsEn: ["lacks context", "overgeneralization"],
        reveal: "Đúng ở một số khu vực hoang dã, nhưng ở Úc và VN, phần lớn cháy rừng do con người gây ra (đốt rừng, bất cẩn). Cần ngữ cảnh địa lý cụ thể.",
        revealEn: "True in some wilderness areas, but in Australia and Vietnam, most forest fires are human-caused (burning, carelessness). Needs specific geographical context.",
        actionHint: "Yêu cầu bổ sung ngữ cảnh hoặc kiểm chứng.",
        actionHintEn: "Request additional context or fact-check.",
        sourceHint: "Báo cáo từ CSIRO, Global Forest Watch",
        sourceHintEn: "Reports from CSIRO, Global Forest Watch"
    },
    {
        id: "c012",
        title: "Tắt điều hòa tiết kiệm điện gấp 10 lần so với tăng nhiệt độ 1°C",
        titleEn: "Turning off AC saves 10x more electricity than raising temperature by 1°C",
        topic: "tiêu dùng",
        topicEn: "consumer",
        credibility: 40,
        type: "misleading",
        baseVirality: 2,
        signals: ["số liệu phóng đại", "thiếu nguồn"],
        signalsEn: ["exaggerated figures", "no source"],
        reveal: "Tắt điều hòa tiết kiệm nhiều điện hơn, nhưng 'gấp 10 lần' là phóng đại. Tăng 1°C tiết kiệm ~10%, tắt hẳn là 100%. Cần ngữ cảnh cụ thể.",
        revealEn: "Turning off AC saves more electricity, but '10x' is exaggerated. Raising 1°C saves ~10%, turning off completely is 100%. Needs specific context.",
        actionHint: "Yêu cầu nguồn và số liệu chính xác.",
        actionHintEn: "Request source and accurate figures.",
        sourceHint: "Tham khảo hướng dẫn tiết kiệm điện từ EVN",
        sourceHintEn: "Refer to electricity saving guide from EVN"
    },
    {
        id: "c013",
        title: "Thịt nuôi cấy phát thải carbon cao hơn cả thịt bò truyền thống",
        titleEn: "Lab-grown meat produces more carbon emissions than traditional beef",
        topic: "môi trường",
        topicEn: "environment",
        credibility: 50,
        type: "misleading",
        baseVirality: 2,
        signals: ["thiếu ngữ cảnh", "nghiên cứu còn tranh cãi"],
        signalsEn: ["lacks context", "controversial research"],
        reveal: "Một số nghiên cứu cho thấy vậy nếu dùng nguồn năng lượng hóa thạch. Nhưng nếu dùng năng lượng tái tạo, thịt nuôi cấy sạch hơn nhiều. Cần ngữ cảnh đầy đủ.",
        revealEn: "Some studies show this if using fossil fuel energy. But with renewable energy, lab-grown meat is much cleaner. Needs full context.",
        actionHint: "Kiểm chứng với nhiều nghiên cứu khác nhau.",
        actionHintEn: "Fact-check with multiple different studies.",
        sourceHint: "Good Food Institute, peer-reviewed journals",
        sourceHintEn: "Good Food Institute, peer-reviewed journals"
    },
    {
        id: "c014",
        title: "Chai nhựa sinh học phân hủy hoàn toàn trong 1 tuần",
        titleEn: "Biodegradable plastic bottles decompose completely in 1 week",
        topic: "môi trường",
        topicEn: "environment",
        credibility: 45,
        type: "misleading",
        baseVirality: 2,
        signals: ["quá tốt để thật", "thiếu điều kiện cụ thể"],
        signalsEn: ["too good to be true", "lacks specific conditions"],
        reveal: "Nhựa sinh học cần điều kiện công nghiệp (nhiệt độ cao, vi khuẩn đặc biệt) mới phân hủy nhanh. Trong môi trường tự nhiên có thể mất nhiều tháng hoặc năm.",
        revealEn: "Bioplastics need industrial conditions (high temperature, special bacteria) to decompose quickly. In natural environment may take months or years.",
        actionHint: "Yêu cầu làm rõ điều kiện phân hủy.",
        actionHintEn: "Request clarification on decomposition conditions.",
        sourceHint: "Nghiên cứu từ các tổ chức môi trường uy tín",
        sourceHintEn: "Research from credible environmental organizations"
    },
    {
        id: "c015",
        title: "Hóa chất E-number trong thực phẩm đều độc hại với sức khỏe",
        titleEn: "E-number chemicals in food are all harmful to health",
        topic: "sức khỏe",
        topicEn: "health",
        credibility: 30,
        type: "misleading",
        baseVirality: 2,
        signals: ["khái quát hóa", "gây lo lắng"],
        signalsEn: ["overgeneralization", "fear-mongering"],
        reveal: "E-number là mã số phụ gia thực phẩm của EU. Nhiều E-number an toàn (E300 = vitamin C). Chỉ một số ít có thể gây phản ứng ở người nhạy cảm.",
        revealEn: "E-numbers are EU food additive codes. Many E-numbers are safe (E300 = vitamin C). Only a few may cause reactions in sensitive people.",
        actionHint: "Kiểm chứng từng loại E-number cụ thể.",
        actionHintEn: "Fact-check each specific E-number.",
        sourceHint: "European Food Safety Authority (EFSA)",
        sourceHintEn: "European Food Safety Authority (EFSA)"
    },

    // ====== TRUE (Tin đúng, có nguồn uy tín) ======
    {
        id: "c016",
        title: "Bảo tồn rừng đô thị giúp giảm nhiệt độ bề mặt 1–3°C, nghiên cứu từ ĐH Melbourne",
        titleEn: "Urban forest conservation helps reduce surface temperature by 1-3°C, study from University of Melbourne",
        topic: "môi trường",
        topicEn: "environment",
        credibility: 86,
        type: "true",
        baseVirality: 1,
        signals: ["nguồn viện nghiên cứu", "số liệu định lượng", "có tác giả"],
        signalsEn: ["research institution source", "quantified data", "has author"],
        reveal: "Nghiên cứu được công bố trên tạp chí Nature Climate Change, có peer-review. Rừng đô thị làm mát qua bóng mát và hơi nước.",
        revealEn: "Research published in Nature Climate Change journal, peer-reviewed. Urban forests cool through shade and water vapor.",
        actionHint: "Chia sẻ có trách nhiệm để nâng cao nhận thức.",
        actionHintEn: "Share responsibly to raise awareness.",
        sourceHint: "Kiểm tra bài báo gốc từ Nature hoặc ĐH Melbourne",
        sourceHintEn: "Check original article from Nature or University of Melbourne"
    },
    {
        id: "c017",
        title: "WHO khuyến nghị rửa tay ít nhất 20 giây với xà phòng để phòng bệnh hô hấp",
        titleEn: "WHO recommends washing hands for at least 20 seconds with soap to prevent respiratory diseases",
        topic: "sức khỏe",
        topicEn: "health",
        credibility: 95,
        type: "true",
        baseVirality: 1,
        signals: ["nguồn WHO", "khoa học ứng dụng", "hướng dẫn rõ ràng"],
        signalsEn: ["WHO source", "applied science", "clear guidelines"],
        reveal: "Đây là khuyến nghị chính thức từ WHO, được chứng minh hiệu quả qua nhiều nghiên cứu. 20 giây đủ để loại bỏ phần lớn vi khuẩn, virus.",
        revealEn: "Official WHO recommendation, proven effective through multiple studies. 20 seconds is enough to remove most bacteria and viruses.",
        actionHint: "Chia sẻ để giáo dục cộng đồng.",
        actionHintEn: "Share to educate community.",
        sourceHint: "who.int/health-topics/hand-hygiene",
        sourceHintEn: "who.int/health-topics/hand-hygiene"
    },
    {
        id: "c018",
        title: "Cục An toàn thông tin: Tăng 120% vụ lừa đảo qua mạng xã hội trong quý 2/2024",
        titleEn: "Information Security Department: 120% increase in social media scams in Q2/2024",
        topic: "an ninh số",
        topicEn: "digital security",
        credibility: 90,
        type: "true",
        baseVirality: 1,
        signals: ["nguồn chính phủ", "số liệu cụ thể", "có thời gian"],
        signalsEn: ["government source", "specific data", "has timeframe"],
        reveal: "Báo cáo chính thức từ Cục An toàn thông tin, Bộ TT&TT Việt Nam. Các hình thức phổ biến: giả mạo người quen, lừa đảo đầu tư.",
        revealEn: "Official report from Information Security Department, Ministry of Information and Communications Vietnam. Common forms: impersonating friends, investment scams.",
        actionHint: "Chia sẻ để cảnh báo cộng đồng.",
        actionHintEn: "Share to warn community.",
        sourceHint: "mic.gov.vn/attt",
        sourceHintEn: "mic.gov.vn/attt"
    },
    {
        id: "c019",
        title: "TP.HCM triển khai 500 điểm thu gom rác thải điện tử miễn phí từ tháng 11",
        titleEn: "HCMC deploys 500 free e-waste collection points from November",
        topic: "môi trường",
        topicEn: "environment",
        credibility: 88,
        type: "true",
        baseVirality: 1,
        signals: ["thông tin địa phương", "nguồn chính quyền", "có mốc thời gian"],
        signalsEn: ["local information", "government source", "has timeframe"],
        reveal: "Thông tin từ Sở Tài nguyên & Môi trường TP.HCM. Danh sách điểm thu gom có trên website chính thức.",
        revealEn: "Information from HCMC Department of Natural Resources and Environment. List of collection points available on official website.",
        actionHint: "Chia sẻ để khuyến khích tham gia.",
        actionHintEn: "Share to encourage participation.",
        sourceHint: "Kiểm tra website Sở TN&MT TP.HCM",
        sourceHintEn: "Check HCMC DONRE website"
    },
    {
        id: "c020",
        title: "Nghiên cứu mới: Uống đủ nước (2–3L/ngày) giúp cải thiện trí nhớ ngắn hạn",
        titleEn: "New research: Drinking enough water (2-3L/day) helps improve short-term memory",
        topic: "sức khỏe",
        topicEn: "health",
        credibility: 75,
        type: "true",
        baseVirality: 1,
        signals: ["nghiên cứu có peer-review", "số liệu hợp lý", "không khẳng định tuyệt đối"],
        signalsEn: ["peer-reviewed research", "reasonable data", "no absolute claims"],
        reveal: "Nghiên cứu từ ĐH California, công bố trên Journal of Nutrition. Uống đủ nước giúp não hoạt động tốt hơn, nhưng không phải 'biệt dược'.",
        revealEn: "Research from UC California, published in Journal of Nutrition. Adequate hydration helps brain function better, but not a 'miracle cure'.",
        actionHint: "Chia sẻ để khuyến khích thói quen tốt.",
        actionHintEn: "Share to encourage good habits.",
        sourceHint: "Tìm bài báo gốc từ journal uy tín",
        sourceHintEn: "Find original article from credible journal"
    },

    // ====== SATIRE (Tin châm biếm, hài hước) ======
    {
        id: "c021",
        title: "Chính phủ Úc tuyên bố sẽ thuế 10% ánh nắng mặt trời để 'bảo vệ nguồn tài nguyên'",
        titleEn: "Australian government announces 10% tax on sunlight to 'protect natural resources'",
        topic: "châm biếm",
        topicEn: "satire",
        credibility: 0,
        type: "satire",
        baseVirality: 2,
        signals: ["The Betoota Advocate", "phi lý", "châm biếm"],
        signalsEn: ["The Betoota Advocate", "absurd", "satire"],
        reveal: "Đây là bài từ The Betoota Advocate, tờ báo châm biếm nổi tiếng của Úc. Không phải tin thật, chỉ là hài hước.",
        revealEn: "This is from The Betoota Advocate, Australia's famous satire newspaper. Not real news, just humor.",
        actionHint: "Không chia sẻ như tin thật. Có thể thích nếu hiểu đây là châm biếm.",
        actionHintEn: "Don't share as real news. Can like if you understand it's satire.",
        sourceHint: "Kiểm tra nguồn - The Betoota Advocate là báo châm biếm",
        sourceHintEn: "Check source - The Betoota Advocate is satire news"
    },
    {
        id: "c022",
        title: "Sinh viên RMIT phát minh ra máy chữa trì hoãn bằng cách... tạo deadline mới mỗi giờ",
        titleEn: "RMIT student invents procrastination cure by... creating new deadlines every hour",
        topic: "châm biếm",
        topicEn: "satire",
        credibility: 5,
        type: "satire",
        baseVirality: 1,
        signals: ["hài hước", "phi lý", "không có nguồn chính thức"],
        signalsEn: ["humorous", "absurd", "no official source"],
        reveal: "Đây là bài đăng hài hước trên mạng xã hội sinh viên, không phải tin thật. Nhưng cũng là cách nói về vấn đề trì hoãn phổ biến.",
        revealEn: "This is a humorous post on student social media, not real news. But it does address the common procrastination issue.",
        actionHint: "Thích và chia sẻ cho vui, nhưng không hiểu nhầm là tin thật.",
        actionHintEn: "Like and share for fun, but don't mistake it for real news.",
        sourceHint: "Đây là meme/humor post từ cộng đồng sinh viên",
        sourceHintEn: "This is a meme/humor post from student community"
    },

    // ====== ADDITIONAL CARDS (Bổ sung đa dạng chủ đề) ======
    {
        id: "c023",
        title: "Sữa hạt luôn 'tốt hơn' sữa bò cho sức khỏe và môi trường",
        titleEn: "Plant milk is always 'better' than cow milk for health and environment",
        topic: "dinh dưỡng",
        topicEn: "nutrition",
        credibility: 48,
        type: "misleading",
        baseVirality: 2,
        signals: ["khái quát hóa", "thiếu ngữ cảnh"],
        signalsEn: ["overgeneralization", "lacks context"],
        reveal: "Phụ thuộc loại sữa hạt (hạnh nhân tốn nhiều nước, đậu nành tốt hơn). Sữa bò có protein và canxi cao hơn. Cần cân nhắc cả dinh dưỡng và môi trường.",
        revealEn: "Depends on plant milk type (almond uses lots of water, soy is better). Cow milk has more protein and calcium. Need to consider both nutrition and environment.",
        actionHint: "Yêu cầu so sánh cụ thể từng loại.",
        actionHintEn: "Request specific comparison of each type.",
        sourceHint: "Nghiên cứu LCA (Life Cycle Assessment) của các loại sữa",
        sourceHintEn: "LCA (Life Cycle Assessment) studies of milk types"
    },
    {
        id: "c024",
        title: "Mẹo đăng ký gói data 'miễn phí trọn đời' chỉ cần gửi tin nhắn đến 8077",
        titleEn: "Trick to register 'lifetime free' data package just send message to 8077",
        topic: "lừa đảo số",
        topicEn: "digital scam",
        credibility: 5,
        type: "false",
        baseVirality: 3,
        signals: ["quá tốt để thật", "không có thông tin nhà mạng chính thức"],
        signalsEn: ["too good to be true", "no official carrier information"],
        reveal: "Đây là lừa đảo. Gửi tin nhắn đến số lạ có thể khiến bạn bị trừ tiền hoặc đăng ký dịch vụ không mong muốn. Luôn kiểm tra với nhà mạng chính thức.",
        revealEn: "This is a scam. Sending messages to unknown numbers may charge you money or subscribe you to unwanted services. Always check with official carrier.",
        actionHint: "Báo cáo ngay lập tức.",
        actionHintEn: "Report immediately.",
        sourceHint: "Kiểm tra website hoặc hotline chính thức của nhà mạng",
        sourceHintEn: "Check official website or hotline of carrier"
    },
    {
        id: "c025",
        title: "Chia sẻ bài này để cứu trợ lũ lụt sẽ đến nhanh hơn - 1 share = 10,000đ",
        titleEn: "Share this post to make flood relief arrive faster - 1 share = 10,000 VND",
        topic: "thiện nguyện",
        topicEn: "charity",
        credibility: 0,
        type: "false",
        baseVirality: 3,
        signals: ["hiểu nhầm quy trình", "khai thác cảm xúc"],
        signalsEn: ["misunderstanding process", "exploiting emotions"],
        reveal: "Chia sẻ trên mạng xã hội KHÔNG trực tiếp chuyển tiền cứu trợ. Muốn hỗ trợ thực sự, hãy quyên góp qua các tổ chức uy tín như Mặt trận Tổ quốc, Hội Chữ thập đỏ.",
        revealEn: "Sharing on social media does NOT directly transfer relief funds. To truly help, donate through credible organizations like Fatherland Front, Red Cross.",
        actionHint: "Không chia sẻ. Hướng dẫn cách quyên góp đúng.",
        actionHintEn: "Don't share. Guide proper donation methods.",
        sourceHint: "Website chính thức của các tổ chức từ thiện uy tín",
        sourceHintEn: "Official websites of credible charity organizations"
    }
];

// Export for use in main.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = cardsData;
}
